[build-system]
requires = ["scikit-build", "setuptools", "wheel", "cmake", "ninja"]
build-backend = "setuptools.build_meta"

[tool.black]
exclude = '''
(
    \.pyi$
)
'''

[tool.pytest.ini_options]
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true
